version: "3.8"
services:
  task_postgres:
    image: postgres:16-alpine
    hostname: task_postgres
    container_name: task_postgres
    restart: unless-stopped
    volumes:
      - .postgres:/var/lib/postgresql/data
    ports:
      - "5443:5432"
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: base
      POSTGRES_PASSWORD: secret
