version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - auth_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  auth_postgres:
    image: postgres:16-alpine
    hostname: auth_postgres
    container_name: auth_postgres
    restart: unless-stopped
    volumes:
      - .postgres:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: base
      POSTGRES_PASSWORD: secret
networks:
  popug_network:
      name: my-proxy-net
      external: true
